const FLAGS: Record<string, string> = {
  "brasil": "🇧🇷",
  "argentina": "🇦🇷",
  "alemanha": "🇩🇪",
  "france": "🇫🇷",
  "franca": "🇫🇷",
  "frança": "🇫🇷",
  "espanha": "🇪🇸",
  "portugal": "🇵🇹",
  "italia": "🇮🇹",
  "itália": "🇮🇹",
  "inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "holanda": "🇳🇱",
  "belgica": "🇧🇪",
  "bélgica": "🇧🇪",
  "croacia": "🇭🇷",
  "croácia": "🇭🇷",
  "uruguai": "🇺🇾",
  "colombia": "🇨🇴",
  "colômbia": "🇨🇴",
  "chile": "🇨🇱",
  "mexico": "🇲🇽",
  "méxico": "🇲🇽",
  "eua": "🇺🇸",
  "estados unidos": "🇺🇸",
  "canada": "🇨🇦",
  "canadá": "🇨🇦",
  "japao": "🇯🇵",
  "japão": "🇯🇵",
  "coreia do sul": "🇰🇷",
  "australia": "🇦🇺",
  "austrália": "🇦🇺",
  "marrocos": "🇲🇦",
  "senegal": "🇸🇳",
  "camaroes": "🇨🇲",
  "camarões": "🇨🇲",
  "nigeria": "🇳🇬",
  "nigéria": "🇳🇬",
  "africa do sul": "🇿🇦",
  "africa": "🇿🇦",
  "egito": "🇪🇬",
  "ghana": "🇬🇭",
  "gana": "🇬🇭",
  "tunísia": "🇹🇳",
  "tunisia": "🇹🇳",
  "russia": "🇷🇺",
  "rússia": "🇷🇺",
  "polônia": "🇵🇱",
  "polonia": "🇵🇱",
  "dinamarca": "🇩🇰",
  "suecia": "🇸🇪",
  "suécia": "🇸🇪",
  "noruega": "🇳🇴",
  "suica": "🇨🇭",
  "suíça": "🇨🇭",
  "austria": "🇦🇹",
  "áustria": "🇦🇹",
  "turquia": "🇹🇷",
  "ucrania": "🇺🇦",
  "ucrânia": "🇺🇦",
  "galés": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "escócia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "irlanda": "🇮🇪",
  "grécia": "🇬🇷",
  "grecia": "🇬🇷",
  "serbia": "🇷🇸",
  "sérvia": "🇷🇸",
  "hungria": "🇭🇺",
  "republica tcheca": "🇨🇿",
  "eslovaquia": "🇸🇰",
  "eslovénia": "🇸🇮",
  "eslovenia": "🇸🇮",
  "albania": "🇦🇱",
  "albânia": "🇦🇱",
  "romenia": "🇷🇴",
  "romênia": "🇷🇴",
  "bulgaria": "🇧🇬",
  "bulgária": "🇧🇬",
  "peru": "🇵🇪",
  "equador": "🇪🇨",
  "venezuela": "🇻🇪",
  "bolivia": "🇧🇴",
  "bolívia": "🇧🇴",
  "paraguai": "🇵🇾",
  "costa rica": "🇨🇷",
  "honduras": "🇭🇳",
  "panama": "🇵🇦",
  "panamá": "🇵🇦",
  "arabia saudita": "🇸🇦",
  "arábia saudita": "🇸🇦",
  "ira": "🇮🇷",
  "irã": "🇮🇷",
  "catar": "🇶🇦",
  "qatar": "🇶🇦",
  "australia": "🇦🇺",
  "nova zelandia": "🇳🇿",
  "nova zelândia": "🇳🇿",
  "china": "🇨🇳",
};

export function getCountryFlag(name: string): string | null {
  const key = name.trim().toLowerCase();
  return FLAGS[key] ?? null;
}
