const COUNTRY_CODES: Record<string, string> = {
  "brasil": "br",
  "argentina": "ar",
  "alemanha": "de",
  "france": "fr",
  "franca": "fr",
  "frança": "fr",
  "espanha": "es",
  "portugal": "pt",
  "italia": "it",
  "itália": "it",
  "inglaterra": "gb-eng",
  "holanda": "nl",
  "países baixos": "nl",
  "belgica": "be",
  "bélgica": "be",
  "croacia": "hr",
  "croácia": "hr",
  "uruguai": "uy",
  "colombia": "co",
  "colômbia": "co",
  "chile": "cl",
  "mexico": "mx",
  "méxico": "mx",
  "eua": "us",
  "estados unidos": "us",
  "canada": "ca",
  "canadá": "ca",
  "japao": "jp",
  "japão": "jp",
  "coreia do sul": "kr",
  "coreia": "kr",
  "australia": "au",
  "austrália": "au",
  "marrocos": "ma",
  "senegal": "sn",
  "camaroes": "cm",
  "camarões": "cm",
  "nigeria": "ng",
  "nigéria": "ng",
  "africa do sul": "za",
  "egito": "eg",
  "ghana": "gh",
  "gana": "gh",
  "tunesia": "tn",
  "tunísia": "tn",
  "russia": "ru",
  "rússia": "ru",
  "polônia": "pl",
  "polonia": "pl",
  "dinamarca": "dk",
  "suecia": "se",
  "suécia": "se",
  "noruega": "no",
  "suica": "ch",
  "suíça": "ch",
  "austria": "at",
  "áustria": "at",
  "turquia": "tr",
  "ucrania": "ua",
  "ucrânia": "ua",
  "gales": "gb-wls",
  "galés": "gb-wls",
  "escocia": "gb-sct",
  "escócia": "gb-sct",
  "irlanda": "ie",
  "grécia": "gr",
  "grecia": "gr",
  "serbia": "rs",
  "sérvia": "rs",
  "hungria": "hu",
  "republica tcheca": "cz",
  "república tcheca": "cz",
  "eslovaquia": "sk",
  "eslováquia": "sk",
  "eslovenia": "si",
  "eslovénia": "si",
  "albania": "al",
  "albânia": "al",
  "romenia": "ro",
  "romênia": "ro",
  "bulgaria": "bg",
  "bulgária": "bg",
  "peru": "pe",
  "equador": "ec",
  "venezuela": "ve",
  "bolivia": "bo",
  "bolívia": "bo",
  "paraguai": "py",
  "costa rica": "cr",
  "honduras": "hn",
  "panama": "pa",
  "panamá": "pa",
  "arabia saudita": "sa",
  "arábia saudita": "sa",
  "ira": "ir",
  "irã": "ir",
  "catar": "qa",
  "qatar": "qa",
  "nova zelandia": "nz",
  "nova zelândia": "nz",
  "china": "cn",
  "indonesia": "id",
  "indonésia": "id",
  "tailandia": "th",
  "tailândia": "th",
  "israel": "il",
  "suécia": "se",
  "finlandia": "fi",
  "finlândia": "fi",
  "irlanda do norte": "gb-nir",
  "luxemburgo": "lu",
  "islandia": "is",
  "islândia": "is",
  "georgia": "ge",
  "geórgia": "ge",
  "haiti": "ht",
  "haïti": "ht",
  "cabo verde": "cv",
  "cabo verde islands": "cv",
  "trinidad e tobago": "tt",
  "trinidad and tobago": "tt",
  "jamaica": "jm",
  "curacao": "cw",
  "curaçao": "cw",
  "suriname": "sr",
  "guiana": "gy",
  "guadalupe": "gp",
  "martinica": "mq",
  "porto rico": "pr",
  "republica dominicana": "do",
  "república dominicana": "do",
  "el salvador": "sv",
  "guatemala": "gt",
  "nicaragua": "ni",
  "nicaragua": "ni",
  "belize": "bz",
  "cuba": "cu",
  "barbados": "bb",
  "bahamas": "bs",
  "tanzania": "tz",
  "tanzânia": "tz",
  "angola": "ao",
  "mocambique": "mz",
  "moçambique": "mz",
  "zambia": "zm",
  "zimbabue": "zw",
  "zimbabwe": "zw",
  "uganda": "ug",
  "ruanda": "rw",
  "rwanda": "rw",
  "kenya": "ke",
  "quenia": "ke",
  "quênia": "ke",
  "etiopia": "et",
  "etiópia": "et",
  "ethiopia": "et",
  "costa do marfim": "ci",
  "ivory coast": "ci",
  "mali": "ml",
  "burkina faso": "bf",
  "guine": "gn",
  "guiné": "gn",
  "guinea": "gn",
  "libia": "ly",
  "líbia": "ly",
  "argelia": "dz",
  "argélia": "dz",
  "algeria": "dz",
  "sudan": "sd",
  "sudao": "sd",
  "sudão": "sd",
  "mozambique": "mz",
  "cape verde": "cv",
  "cape verde islands": "cv",
  "coreia do norte": "kp",
  "north korea": "kp",
  "filipinas": "ph",
  "philippines": "ph",
  "india": "in",
  "índia": "in",
  "paquistao": "pk",
  "paquistão": "pk",
  "bangladesh": "bd",
  "oman": "om",
  "omã": "om",
  "kuwait": "kw",
  "bahrain": "bh",
  "bahrein": "bh",
  "emirados arabes": "ae",
  "emirados árabes": "ae",
  "uae": "ae",
  "jordania": "jo",
  "jordânia": "jo",
  "libano": "lb",
  "líbano": "lb",
  "siria": "sy",
  "síria": "sy",
  "iraque": "iq",
  "iraq": "iq",
  "yemen": "ye",
  "iemen": "ye",
};

export function getCountryFlagUrl(name: string): string | null {
  const key = name.trim().toLowerCase();
  const code = COUNTRY_CODES[key];
  if (!code) return null;
  return `https://flagcdn.com/w80/${code}.png`;
}
