export const sportIcons: Record<string, string> = {
  soccer: "soccer_epl",
  football: "americanfootball_nfl",
  basketball: "basketball_nba",
  baseball: "baseball_mlb",
  hockey: "icehockey_nhl",
  tennis: "tennis_atp",
  mma: "mma_mixed_martial_arts",
  boxing: "boxing_boxing",
  golf: "golf_pga_championship",
  cricket: "cricket_icc_world_cup",
  rugby: "rugbyleague_nrl",
};

export const sportLabels: Record<string, string> = {
  soccer_epl: "Premier League",
  soccer_brazil_campeonato: "Brasileirão",
  soccer_brazil_serie_b: "Série B",
  soccer_uefa_champs_league: "Champions League",
  soccer_uefa_europa_league: "Europa League",
  soccer_spain_la_liga: "La Liga",
  soccer_germany_bundesliga: "Bundesliga",
  soccer_italy_serie_a: "Serie A",
  soccer_france_ligue_one: "Ligue 1",
  americanfootball_nfl: "NFL",
  americanfootball_ncaaf: "NCAA Football",
  basketball_nba: "NBA",
  basketball_ncaab: "NCAA Basketball",
  basketball_euroleague: "EuroLeague",
  baseball_mlb: "MLB",
  icehockey_nhl: "NHL",
  tennis_atp_french_open: "French Open",
  tennis_wta_french_open: "French Open (WTA)",
  mma_mixed_martial_arts: "UFC/MMA",
  boxing_boxing: "Boxing",
};

export const sportGroups: Record<string, { label: string; icon: string }> = {
  Soccer: { label: "Futebol", icon: "soccer" },
  "American Football": { label: "Futebol Americano", icon: "football" },
  Basketball: { label: "Basquete", icon: "basketball" },
  Baseball: { label: "Baseball", icon: "baseball" },
  "Ice Hockey": { label: "Hóquei", icon: "hockey" },
  Tennis: { label: "Tênis", icon: "tennis" },
  "Mixed Martial Arts": { label: "MMA", icon: "mma" },
  Boxing: { label: "Boxe", icon: "boxing" },
  Golf: { label: "Golfe", icon: "golf" },
  Cricket: { label: "Críquete", icon: "cricket" },
  "Rugby League": { label: "Rugby", icon: "rugby" },
};
