// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/page-backgrounds/Campo.tsx": () => import("../components/mockups/page-backgrounds/Campo.tsx"),
  "./components/mockups/page-backgrounds/Geometrico.tsx": () => import("../components/mockups/page-backgrounds/Geometrico.tsx"),
  "./components/mockups/page-backgrounds/Granulado.tsx": () => import("../components/mockups/page-backgrounds/Granulado.tsx"),
  "./components/mockups/page-backgrounds/Marmore.tsx": () => import("../components/mockups/page-backgrounds/Marmore.tsx")
};
